version: '3.8'

services:
  stock-alert-server:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stock-alert-network

networks:
  stock-alert-network:
    driver: bridge
